# Generated by Django 3.0.2 on 2021-05-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
